LINKEDIN_EMAIL = '[EMAIL]' # YOUR LINKEDIN EMAIL GOES HERE
LINKEDIN_PASSWORD = '[PASSWORD]' # YOUR LINKEDIN PASSWORD GOES HERE
PAGE_COUNT = 1 # RANGE MUST BE BETWEEN 1 - 100
NAME_OF_OUTPUT_FILE = 'ALL_CEO_DETAILS' # PROVIDE OUTPUT FILENAME 
